# Generated by Django 3.1.3 on 2022-11-24 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='Customer',
    #         fields=[
    #             ('order_num', models.BigAutoField(primary_key=True, serialize=False)),
    #             ('date', models.DateTimeField(auto_now_add=True)),
    #             ('gender', models.CharField(blank=True, max_length=50)),
    #             ('age_group', models.CharField(blank=True, max_length=255)),
    #             ('total_num', models.IntegerField(default=0)),
    #             ('total_price', models.IntegerField(default=0)),
    #         ],
    #     ),
    #     migrations.CreateModel(
    #         name='List',
    #         fields=[
    #             ('food_num', models.BigAutoField(primary_key=True, serialize=False)),
    #             ('food_name', models.CharField(max_length=200)),
    #             ('price', models.IntegerField(default=0)),
    #             ('food_explain', models.TextField(blank=True, max_length=2000)),
    #             ('category', models.CharField(max_length=250)),
    #             ('image', models.ImageField(blank=True, upload_to='static/menuimg/')),
    #         ],
    #     ),
    #     migrations.CreateModel(
    #         name='Favor',
    #         fields=[
    #             ('favor_num', models.BigAutoField(primary_key=True, serialize=False)),
    #             ('under30m', models.IntegerField(default=0, null=True)),
    #             ('under50m', models.IntegerField(default=0, null=True)),
    #             ('upper50m', models.IntegerField(default=0, null=True)),
    #             ('under30f', models.IntegerField(default=0, null=True)),
    #             ('under50f', models.IntegerField(default=0, null=True)),
    #             ('upper50f', models.IntegerField(default=0, null=True)),
    #             ('total_order', models.IntegerField(default=0, null=True)),
    #             ('food_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.list')),
    #         ],
    #     ),
    #     migrations.CreateModel(
    #         name='Bill',
    #         fields=[
    #             ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('menu_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.list')),
    #             ('order_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
    #         ],
    #     ),
    # ]
