# Generated by Django 4.1.4 on 2022-12-08 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("order_num", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("gender", models.CharField(blank=True, max_length=50)),
                ("age_group", models.CharField(blank=True, max_length=255)),
                ("total_num", models.IntegerField(default=0)),
                ("total_price", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="List",
            fields=[
                ("food_num", models.BigAutoField(primary_key=True, serialize=False)),
                ("food_name", models.CharField(max_length=200)),
                ("price", models.IntegerField(default=0)),
                ("food_explain", models.TextField(blank=True, max_length=2000)),
                ("category", models.CharField(max_length=250)),
                ("image", models.ImageField(blank=True, upload_to="static/menuimg/")),
                ("modify_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("M20", models.IntegerField(default=0, null=True)),
                ("M30", models.IntegerField(default=0, null=True)),
                ("M40", models.IntegerField(default=0, null=True)),
                ("M50", models.IntegerField(default=0, null=True)),
                ("M60", models.IntegerField(default=0, null=True)),
                ("M70", models.IntegerField(default=0, null=True)),
                ("W20", models.IntegerField(default=0, null=True)),
                ("W30", models.IntegerField(default=0, null=True)),
                ("W40", models.IntegerField(default=0, null=True)),
                ("W50", models.IntegerField(default=0, null=True)),
                ("W60", models.IntegerField(default=0, null=True)),
                ("W70", models.IntegerField(default=0, null=True)),
                (
                    "food_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.list"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("active", models.BooleanField(default=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.list"
                    ),
                ),
            ],
            options={"db_table": "CartItem",},
        ),
    ]
