# Generated by Django 3.1.3 on 2022-12-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bill_cartitem_customer_favor_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='age_and_gender',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
