# Generated by Django 4.1.4 on 2022-12-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="M20",),
        migrations.RemoveField(model_name="order", name="M30",),
        migrations.RemoveField(model_name="order", name="M40",),
        migrations.RemoveField(model_name="order", name="M50",),
        migrations.RemoveField(model_name="order", name="M60",),
        migrations.RemoveField(model_name="order", name="M70",),
        migrations.RemoveField(model_name="order", name="W20",),
        migrations.RemoveField(model_name="order", name="W30",),
        migrations.RemoveField(model_name="order", name="W40",),
        migrations.RemoveField(model_name="order", name="W50",),
        migrations.RemoveField(model_name="order", name="W60",),
        migrations.RemoveField(model_name="order", name="W70",),
        migrations.AddField(
            model_name="list",
            name="M20",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="list",
            name="M30",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="list",
            name="M40",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="list",
            name="M50",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="list",
            name="M60",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="list",
            name="M70",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="list",
            name="W20",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="list",
            name="W30",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="list",
            name="W40",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="list",
            name="W50",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="list",
            name="W60",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="list",
            name="W70",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
