# Generated by Django 3.1.3 on 2022-12-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_list_age_and_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='age_and_gender',
        ),
    ]
