# Generated by Django 4.1.4 on 2022-12-08 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_list_modify_date"),
    ]

    operations = [
        migrations.DeleteModel(name="Customer",),
    ]
